Fix code to reuse pipeline image
The code from 41ce3a5e8b906cbbb902578f56194e9b789a0cb5 wasn't getting properly the fake image name. For instance, instead of `myproject-odoo:10.0` it was getting `myproject-odoo:latest`.

Besides, the code is simplified to avoid a multiline script that would be harder to debug in Gitlab CI logs.

Now, the pipeline image is detected with the same system as the real image. If there's no real image, it will fail. If re-tagging fails, the process will not fail.

diff --git a/examples/.gitlab-ci.yml b/examples/.gitlab-ci.yml
--- a/examples/.gitlab-ci.yml
+++ b/examples/.gitlab-ci.yml
@@ -47,13 +47,16 @@ Rebuild without cache and push: &rebuild
   only: &main_branches
     - /^\d+\.\d+$/
   script:
-    - fake_image="$ODOO_IMAGE"
+    # Obtain the odoo image being used in the pipeline
+    - pipeline_image="$(docker-compose config | yq -r .services.odoo.image)"
+    # Obtain the real odoo image name that will be pushed
     - export -n ODOO_IMAGE
     - real_image="$(docker-compose config | yq -r .services.odoo.image)"
-    - |
-      if [ -n "$fake_image" -a "$real_image" != "null" ]; then
-        docker image tag "$fake_image" "$real_image"
-      fi
+    # Fail if there's no real image to push
+    - test -n "$real_image" -a "$real_image" != "null"
+    # Rename pipeline image with real image name if possible
+    - docker image tag "$pipeline_image" "$real_image" || true
+    # Use or not cache depending on $BUILD_FLAGS for the job
     - build
     - docker-compose push
 
